### DISCUSSION TITLE
What should this gh-action do

### DISCUSSION THREAD

**Discussion by epijim** [insightsengineering/r-pkg-installation-validation#1] [Ideas]
Primary aim is to show that a gh-action can, on each release of a version (I would assume that most packages use releases, rather than just tracking `master`/`main`. We then add this to our open sourced R packages to provide some transperancy on how the installation of the package is on a common system (e.g. rocker:4.0.1 on ubuntu).

Short term I'd be happy to focus on quite a generic document, that simply is an `rmd` prints the output of:

- `sessionInfo()`, `capabilities()` and `.libPaths()`
- what container the gh-action is using? 
- get's some core metadata from the Description like maintainer, description, imports, depends, suggests and version (and this could be crude calls to `read.dcf` for now
- `covr::package_coverage()`
- `covtracer::test_trace_df()`
- `rcmdcheck::rcmdcheck()`

And then allows the user to easily edit the key validation topics (but we can have some example content in the example template). With headings like those we use internally:

```
## Validation Plan
## Terms and abbreviations
## User requirements specification
## System description
## Solution archeticture
## Test Plan
```

And then adding it is super easy. e.g. use just needs to add this code (plus the template).

```
---
name: R Package Validation report

on:
  release:
    types: [published]

jobs:
  r-pkg-validation:
    runs-on: ubuntu-latest
    container: rocker/verse:4.1.0 # also versions packages installed via install.packages()
    steps:
      - uses: actions/checkout@v2
      - name: Build report
        uses: insightsengineering/r-pkg-validation@main
        with:
          # R package root path, in case your R package is within a subdirectory of the repo
          path: "."
          # Template location
          template_path: ".github/validation_template.rmd"
          # Output type
          output_type: "pdf"
```

And we get this up quickly (maybe @dinakar29's team can look into it?) - but we make sure not to spend too much time on it, as potentially valtools could be refactored to automate the documentation to test linkage, and when that happens we could refactor the backend to lean more on their setup.

@dgkf - super keen to get your thoughts on this.
