### ISSUE TITLE
Ensure built report attached to release (if action set to run on releases)

### ISSUE THREAD

**Issue by epijim** [insightsengineering/r-pkg-installation-validation#10]
As per title - expected is use case is with a release, so ideally action would attach the built artifact (e.g. pdf) to release.

**Comment by epijim** [comment]
Should we make this something the user does? e.g. right now for testing I'm using below:

```
      - name: Upload visR validation report
        uses: actions/upload-artifact@v2
        if: success()
        with:
          name: visR-report.pdf
          path: ./validation-report.pdf
          if-no-files-found: error
```

As it's on a branch - but most users would want to attach it to a release, but that would require quite different code... (from what I saw on the docs we should use the action to create the release?)
